import java.awt.BorderLayout;
import java.awt.Component;

import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;


/**
 *
 * @author akash
 */
public class UserRegistrationGUI extends javax.swing.JFrame {

	private JTable jtable1; // the table displayed on the GUI
    private UserRegistrationTableController UserRegistrationTableController; // glue between model and gui
    
    /**
     * Creates new form UserRegistrationGUI
     */
    public UserRegistrationGUI() {
        initComponents();
        UserRegistrationTableController = new UserRegistrationTableController(this);
        addButtonJTable();
    }
    
    public void addButtonJTable() {
		// addButton the data and column names to a JTable
		//jtable1  = new JTable(UserListTableController.getData(), UserListTableController.getColumnNames());
	   
	    jtable1 = new JTable(UserRegistrationTableController.getTableModel());
		// addButton a ListSelectionListener to the table
		jtable1.getSelectionModel().addListSelectionListener(UserRegistrationTableController);
		
		// addButton the table to a scrollpane
		JScrollPane scrollpane = new JScrollPane(jtable1);
		UserListTablePanel.setLayout(new BorderLayout());
		UserListTablePanel.add(scrollpane, BorderLayout.CENTER);
    }
    
    public void updateTable() {
    	jtable1.setModel(UserRegistrationTableController.getTableModel());
    }

	public void setPasswordTextField(String val) {
		passwordTextField.setText(val);
	}

	public void setUserIDTextField(String val) {
		userIDTextField.setText(val);;
	}

	public void setUserNameTextField(String val) {
		userNameTextField.setText(val);
	}
	


	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        UserRegistrationPanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        typeOfUserLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        UserListTablePanel = new javax.swing.JPanel();
        addUserButton = new javax.swing.JButton();
        deleteUserButton = new javax.swing.JButton();
        updateUserButton = new javax.swing.JButton();
        userIDLabel = new javax.swing.JLabel();
        userIDTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UserRegistrationPanel.setBackground(new java.awt.Color(255, 255, 153));
        UserRegistrationPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 0, 13), new java.awt.Color(255, 0, 0))); // NOI18N

        userNameLabel.setText("User Name:");

        passwordLabel.setText("Password:");

        typeOfUserLabel.setText("Type of User:");

        jRadioButton1.setText("Normal Administrator");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Viewer");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        UserListTablePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("User List Table"));

        javax.swing.GroupLayout UserListTablePanelLayout = new javax.swing.GroupLayout(UserListTablePanel);
        UserListTablePanel.setLayout(UserListTablePanelLayout);
        UserListTablePanelLayout.setHorizontalGroup(
            UserListTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        UserListTablePanelLayout.setVerticalGroup(
            UserListTablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );

        addUserButton.setLabel("Add ");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        deleteUserButton.setLabel("Delete ");
        deleteUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserButtonActionPerformed(evt);
            }
        });
        
        updateUserButton.setLabel("Update ");
        updateUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserButtonActionPerformed(evt);
            }
        });
        
        userIDLabel.setText("User ID:");

        userIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userIDTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserRegistrationPanelLayout = new javax.swing.GroupLayout(UserRegistrationPanel);
        UserRegistrationPanel.setLayout(UserRegistrationPanelLayout);
        UserRegistrationPanelLayout.setHorizontalGroup(
            UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegistrationPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserRegistrationPanelLayout.createSequentialGroup()
                        .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserRegistrationPanelLayout.createSequentialGroup()
                                .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userNameLabel)
                                    .addComponent(passwordLabel))
                                .addGap(18, 18, 18)
                                .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserRegistrationPanelLayout.createSequentialGroup()
                                .addComponent(addUserButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteUserButton)))
                        .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserRegistrationPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(userIDLabel)
                                .addGap(45, 45, 45)
                                .addComponent(userIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(UserRegistrationPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(updateUserButton))
                            .addGroup(UserRegistrationPanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(typeOfUserLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton1)))))
                    .addComponent(UserListTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        UserRegistrationPanelLayout.setVerticalGroup(
            UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserRegistrationPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNameLabel)
                    .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIDLabel)
                    .addComponent(userIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeOfUserLabel)
                    .addComponent(jRadioButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addGroup(UserRegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserButton)
                    .addComponent(deleteUserButton)
                    .addComponent(updateUserButton))
                .addGap(5, 5, 5)
                .addComponent(UserListTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(UserRegistrationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(UserRegistrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	//addButton a row to the table
    	String[] array = new String[jtable1.getColumnCount()];
    	array[0] = userIDTextField.getText();
    	array[1] = userNameTextField.getText();
    	array[2] = passwordTextField.getText(); 
    	if(jRadioButton1.isSelected()){
    		array[3] = jRadioButton1.getText();
    	}
    	else if(jRadioButton2.isSelected()){
    		array[3] = jRadioButton2.getText();
    	}
    	
    	Component controllingFrame = null;
    	if(array[0] != null && array[1] != null && array[2] != null && array[3] != null){
    		int count = 0;
        	for(int row = 0; row <= jtable1.getRowCount() - 1; row++) {
        		if(jtable1.getValueAt(row, 0).equals(array[0])){
        			JOptionPane.showMessageDialog( controllingFrame,
                            "You need to enter a unique user ID number that was not used before.",
                            "Error Message",
                            JOptionPane.ERROR_MESSAGE);
        			count++;
        		}	
        	}
    		if(count == 0){
    			UserRegistrationTableController.addRow(array);
    		}
    	}
    	else{
			JOptionPane.showMessageDialog( controllingFrame,
                    "You need to input values for all text fields and radio buttons",
                    "Error Message",
                    JOptionPane.ERROR_MESSAGE);
    	}
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void userIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }
    
    private void deleteUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    	int index = jtable1.getSelectedRow();
    	int userID = Integer.parseInt((String) UserRegistrationTableController.getTableModel().getValueAt(index, 0));
    	UserRegistrationTableController.deleteRow(userID);
    	jtable1.revalidate();
    }                                                

    private void updateUserButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    	//addButton a row to the table
    	//int index = jtable1.getSelectedRow();
    	String[] array = new String[jtable1.getColumnCount()];
    	array[0] = userIDTextField.getText();
    	array[1] = userNameTextField.getText();
    	array[2] = passwordTextField.getText(); 
    	if(jRadioButton1.isSelected()){
    		array[3] = jRadioButton1.getText();
    	}
    	else if(jRadioButton2.isSelected()){
    		array[3] = jRadioButton2.getText();
    	}
    	
    	Component controllingFrame = null;
    	if(array[0] != null && array[1] != null && array[2] != null && array[3] != null){
    		UserRegistrationTableController.updateRow(array);
    	}
    	else{
			JOptionPane.showMessageDialog( controllingFrame,
                    "You need to input values for all text fields and radio buttons",
                    "Error Message",
                    JOptionPane.ERROR_MESSAGE);
    	}
    }  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserRegistrationGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
          } catch (Exception  e) {
            System.err.println("Unable to find and load driver");
            System.exit(1);
         }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserRegistrationGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel UserListTablePanel;
    private javax.swing.JPanel UserRegistrationPanel;
    private javax.swing.JButton addUserButton;
    private javax.swing.JButton deleteUserButton;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JLabel typeOfUserLabel;
    private javax.swing.JButton updateUserButton;
    private javax.swing.JLabel userIDLabel;
    private javax.swing.JTextField userIDTextField;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration                   
}


